export {default as AboutPage} from './AboutPage'
export {default as CareerPath} from './CareerPathPage'
export {default as HomePage} from './HomePage'
export {default as NotFoundPage} from './NotFoundPage'
export {default as ProjectDetail} from './ProjectDetailsPage'
export {default as ProjectsPage} from './ProjectsPage'
export {default as Impressum} from './ImpressumPage'
export {default as Datenschutz} from './DatenschutzPage'